dist: xenial
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - pypy3.5

cache:
  directories:
    - $PWD/wheelhouse
env:
  global:
    - PIP_FIND_LINKS=$PWD/wheelhouse

# command to install dependencies
install:
  - pip install tox .
script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')
